"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from datetime import datetime


def triangle(n):
    return n*(n+1)/2


def count_div(n):
    i = 2
    limit = int(n ** 0.5)
    c = 2 + (n % limit == 0)
    while i < limit:
        c += 2 * (n % i == 0)
        i += 1
    return c


i = 1
d = 0
a = datetime.now()
while d <= 500:
    d = count_div(triangle(i))
    i += 1

print(triangle(i-1))
print(datetime.now() - a)